# Metaheuristics - Optimisation Lab

## Problem 1

This problem is to use sensitivity analysis on revenue management for a very simplified airline pricing model. We will assume that an airline has one flight per day from Boston to Atlanta and they use an airplane that seats 150 people. 
The airline wishes to determine 3 prices, $p_i, i = (1,2,3)$, linked to 3 fare buckets. The fare buckets are designed to maximize revenue by separating travelers into groups. The airline models demand for seats in each group using the formula:
$D_{i} = a_{i}*exp(-1/a_{i}*p_{i})$ 

Where D_i is the people that want to fly given price p_i, and the remaining parameters are a_1=100, a_2=150, and a_3=300. 
For simplicity we assume that each $D_{i}$ is a continuous variable.

Decision variable: $p_i$

Constraints: 
* sold seats $\le 150$

* $p_i \ge 0$

We can formulate the revenue maximization problem for this flight as : 

$$Max \sum D_{i} * p_{i}$$

Which is equivalent to: 

Min f(x) with 

$f(x) = -\sum D_{i} * p_{i}$

$x = [p_{1},p_{2},p_{3}]$

$D_{i} = a_{i}*exp(-1/a_{i}*p_{i})$

with the constraint:
$ \sum D_{i} \le 150 <=> 150 -\sum D_{i} \le0  $ 

In [130]:
import numpy as np
from scipy.optimize import minimize
 
a1=100
a2=150
a3=300

total_seats = 150 

def f(x): #function we'd like to minimize 
    x1,x2,x3 = x
    return -(a1*np.exp(-1/a1*x1)*x1 + a2*np.exp(-1/a2*x2)*x2 + a3*np.exp(-1/a3*x3)*x3)

def demand(x):
    x1,x2,x3 = x
    return a1*np.exp(-1/a1*x1) + a2*np.exp(-1/a2*x2) + a3*np.exp(-1/a3*x3)   
 
x0 = np.array([500, 400, 100]) # first values for optimisation algo

# create constraints
def apply_constraint(x):
    x1,x2,x3 = x
    return total_seats - demand(x)

my_constraints = ({'type': 'eq', 
                   "fun": apply_constraint})

#Quasi Newton Quadratic as ??  
res1 = minimize(f, x0, method='SLSQP', options={'disp': True}, constraints=my_constraints)
x = res1.x

# optimal prices - temporary as they yield float numbers for the demand
p1=x[0]
p2=x[1]
p3=x[2]


# Number of people expected to buy each ticket
# It has to be integer values, and their sum should equal 150 
n1 = int(round(a1*np.exp(-1/a1*p1)))
n2 = int(round(a2*np.exp(-1/a2*p2)))
n3 = int(round(a3*np.exp(-1/a3*p3)))
total_tickets = n1+n2+n3
## todo: add a condition if total_tickets ≠ 150

# Now that we have plausible values for our n_i we can update our prices to match. 
# n_i = a_i * exp(-1/a_i * p_i) <=> (n_i/a_i >0) p_i = -a_i * ln(n_i/a_i)
p1 = round(-a1 * np.log(n1/a1),2)
p2 = round(-a2 * np.log(n2/a2),2)
p3 = round(-a3 * np.log(n3/a3),2)
optimal_revenue = round(p1*n1 + p2*n2+p3*n3,2)

print("-"*50)
print(p1, " optimal price 1")
print(p2, " optimal price 2")
print(p3, " optimal price 3")
print(optimal_revenue, "expected optimal revenue")


print("-"*50)
print(n1, " people expected to buy at price 1")
print(n2, " people expected to buy at price 2")
print(n3, " people expected to buy at price 3")
print(total_tickets, "total tickets sold")

Optimization terminated successfully.    (Exit mode 0)
            Current function value: -43670.85883481112
            Iterations: 18
            Function evaluations: 103
            Gradient evaluations: 18
--------------------------------------------------
156.06  optimal price 1
205.96  optimal price 2
357.88  optimal price 3
43670.82 expected optimal revenue
--------------------------------------------------
21  people expected to buy at price 1
38  people expected to buy at price 2
91  people expected to buy at price 3
150 total tickets sold


Notes / next steps on this exercise:
- Verify after converting final numbers to integer that I have reached 150 tickets, and if not provide a way to deal with it
- Do some research to find an integer algorithm (and implement) so I don't have to do the above 
- Simplify / clean code

### Adding 3 seats

In [132]:
total_seats = 153
def apply_constraint(total_seats,x):
    x1,x2,x3 = x
    # Total number of seats = 153 
    return total_seats - demand(x)

my_constraints = ({'type': 'eq', 
                   "fun": apply_constraint })

res2 = minimize(f, x0, method='SLSQP', options={'disp': True}, constraints=my_constraints)
x = res2.x

# optimal prices - temporary as they yield float numbers for the demand
p1=x[0]
p2=x[1]
p3=x[2]


# Number of people expected to buy each ticket
# It has to be integer values, and their sum should equal 150 
n1 = int(round(a1*np.exp(-1/a1*p1)))
n2 = int(round(a2*np.exp(-1/a2*p2)))
n3 = int(round(a3*np.exp(-1/a3*p3)))
total_tickets = n1+n2+n3
## todo: add a condition if total_tickets ≠ total_seats

# Now that we have plausible values for our n_i we can update our prices to match. 
# n_i = a_i * exp(-1/a_i * p_i) <=> (n_i/a_i >0) p_i = -a_i * ln(n_i/a_i)
p1 = round(-a1 * np.log(n1/a1),2)
p2 = round(-a2 * np.log(n2/a2),2)
p3 = round(-a3 * np.log(n3/a3),2)
optimal_revenue = round(p1*n1 + p2*n2+p3*n3,2)

print("-"*50)
print(p1, " optimal price 1")
print(p2, " optimal price 2")
print(p3, " optimal price 3")
print(optimal_revenue, "expected optimal revenue")


print("-"*50)
print(n1, " people expected to buy at price 1")
print(n2, " people expected to buy at price 2")
print(n3, " people expected to buy at price 3")
print(total_tickets, "total tickets sold")

Optimization terminated successfully.    (Exit mode 0)
            Current function value: -43835.26961528414
            Iterations: 20
            Function evaluations: 102
            Gradient evaluations: 20
--------------------------------------------------
151.41  optimal price 1
202.06  optimal price 2
351.35  optimal price 3
43886.91 expected optimal revenue
--------------------------------------------------
22  people expected to buy at price 1
39  people expected to buy at price 2
93  people expected to buy at price 3
154 total tickets sold


In [ ]:
# Issue as my total number of tickets sold ≠153.
if total_tickets > total_seats:
    

In [6]:
def con(p):
    p1 = p[0]
    p2 = p[1]
    p3 = p[2]
    a = [100,150,300]
    return 150 -( a[0]*exp(-1/a[0]*p1)+a[1]*exp(-1/a[1]*p2)+a[2]*exp(-1/a[2]*p3) )

In [8]:
a1=100 
a2=150
a3=300

In [9]:
def demand(p):
    p1 = p[0]
    p2 = p[1]
    p3 = p[2]
    return a1*np.exp(-1/a1*p1)+a2*np.exp(-1/a2*p2)+a3*np.exp(-1/a3*p3)


In [22]:
def revenue(p):
    p1 = p[0]
    p2 = p[1]
    p3 = p[2]
    return p1*a1*np.exp(-1/a1*p1)+p2*a2*np.exp(-1/a2*p2)+p3*a3*np.exp(-1/a3*p3)   

In [23]:
p_s = [[0,0,1000],
      [0,1000,0],
      [0,0,1000],
      [1000,1000,1000]]
for p in p_s:
    print(revenue(p))
    
x<- np.linspace(0,100, 100)
y<- np.linspace(0,100, 100)
z<- np.linspace(0,100, 100)


10702.198004175718
190.8950702009712
10702.198004175718
10897.633067352937


## Problem 2 

In [34]:
from scipy import optimize
import numpy as np

def f(x):
    x1 = x[0]
    x2 = x[1]
    return 100*(x2-x1**2)**2 + (1-x1)**2


In [56]:
# Testing that everything works 
x0=10*np.random.random_sample(2)-5 #random number between -5 and 5
cg1 = optimize.fmin_cg(f, x0, retall=True) #using scipy conjugate gradient algorithm
cg1[1]

Optimization terminated successfully.
         Current function value: 0.000000
         Iterations: 30
         Function evaluations: 260
         Gradient evaluations: 65


[array([3.11962764, 1.52618025]),
 array([2.12234518, 1.68595408]),
 array([-0.21048963,  2.23502786]),
 array([-0.76127878,  1.01526825]),
 array([-0.92475094,  0.90497324]),
 array([-0.9419696 ,  0.89320443]),
 array([-0.77190377,  0.56422584]),
 array([-0.54033856,  0.24792539]),
 array([-0.49726564,  0.25919971]),
 array([-0.29854411,  0.0480353 ]),
 array([-0.2552443 ,  0.01565204]),
 array([-0.16039637,  0.04534047]),
 array([-0.00610564, -0.02504216]),
 array([ 0.05946245, -0.0329833 ]),
 array([0.16810512, 0.03101492]),
 array([0.21749392, 0.03291475]),
 array([0.29921556, 0.06598782]),
 array([0.56576988, 0.33170179]),
 array([0.59498149, 0.35012115]),
 array([0.62723255, 0.38175488]),
 array([0.65709017, 0.41551695]),
 array([0.80325954, 0.63457877]),
 array([0.79901944, 0.6375611 ]),
 array([0.88118787, 0.76998901]),
 array([0.96772863, 0.94105642]),
 array([0.98795411, 0.9767406 ]),
 array([0.98825341, 0.97660146]),
 array([0.9884877 , 0.97692123]),
 array([0.999894  , 0.99

In [75]:
#Recording severals runs
from pandas import DataFrame
import numpy as np

starting_points = []
final_points = []
iterations = []
for i in range(10):
    start_point = 10*np.random.random_sample(2) -5 #random number between -5 and 5
    starting_points.append(start_point)
    run = optimize.fmin_cg(f, start_point, retall=True)
    final_points.append(run[0])
    iterations.append(len(run[1])-1)

data = {'starting_points':starting_points, 'final_points':final_points, 'iterations':iterations} 
eggcrate = DataFrame(data, columns = ["starting_points", "final_points", "iterations"])
eggcrate

Optimization terminated successfully.
         Current function value: 0.000000
         Iterations: 20
         Function evaluations: 181
         Gradient evaluations: 45
Optimization terminated successfully.
         Current function value: 0.000000
         Iterations: 31
         Function evaluations: 276
         Gradient evaluations: 69
Optimization terminated successfully.
         Current function value: 0.000000
         Iterations: 21
         Function evaluations: 212
         Gradient evaluations: 52
Optimization terminated successfully.
         Current function value: 0.000000
         Iterations: 24
         Function evaluations: 224
         Gradient evaluations: 56
Optimization terminated successfully.
         Current function value: 0.000000
         Iterations: 31
         Function evaluations: 300
         Gradient evaluations: 75
Optimization terminated successfully.
         Current function value: 0.000000
         Iterations: 21
         Function evaluations: 

starting_points  \
0  [-3.7333210725330543, 1.7331801665707491]   
1  [3.8852892353172663, -0.5094890681791941]   
2  [-2.46222788009852, -0.42976903846463355]   
3   [4.959937806051649, 0.17871575464580491]   
4  [4.3706252456879735, -1.1554534149695614]   
5  [-1.2804592470342802, 0.1231404130238909]   
6  [0.5338696146312571, -2.1990998617611615]   
7    [-3.319062622968337, 3.762443998176545]   
8    [0.6907567323565384, 2.265756993428374]   
9   [3.6015727318441346, 1.3162250649392249]   

                               final_points  iterations  
0    [0.99999893487809, 0.9999978687261567]          20  
1  [0.9999976223282595, 0.9999952351810634]          31  
2  [1.0000010924175102, 1.0000022014743066]          21  
3  [0.9999965457979195, 0.9999930882362016]          24  
4  [0.9999992076110427, 0.9999984154960204]          31  
5  [0.9999955148518569, 0.9999910222185404]          21  
6  [0.9999918351644101, 0.9999829544739731]          17  
7  [0.9999955219676849, 0.9999910359269577]          35  
8  [0.9999954724265822, 0.9999909371821595]          14  
9  [0.9999954478812709, 0.9999908879993026]          34

In [97]:
#Package previous code into a function
def runs(f, len_x, up, lb, number_runs=10):
    starting_points = []
    final_points = []
    iterations = []
    for i in range(number_runs):
        start_point = (up-lb)*np.random.random_sample(len_x) + lb #random number between lb and up
        starting_points.append(start_point)
        run = optimize.fmin_cg(f, start_point, retall=True)
        final_points.append(run[0])
        iterations.append(len(run[1])-1)

    data = {'starting_points':starting_points, 'final_points':final_points, 'iterations':iterations} 
    df = DataFrame(data, columns = ["starting_points", "final_points", "iterations"])
    return df

In [98]:
def banana(x):
    x1 = x[0]
    x2 = x[1]
    return 100*(x2-x1**2)**2 + (1-x1)**2

def eggcrate(x):
    x1 = x[0]
    x2 = x[1]
    return x1**2 + x2**2 + 25*(np.sin(x1)**2+np.sin(x2)**2)

banana_min = runs(banana, len_x=2, up=5, lb=-5, number_runs=15)
banana_min

Optimization terminated successfully.
         Current function value: 0.000000
         Iterations: 16
         Function evaluations: 144
         Gradient evaluations: 36
Optimization terminated successfully.
         Current function value: 0.000000
         Iterations: 25
         Function evaluations: 266
         Gradient evaluations: 65
         Current function value: 0.000000
         Iterations: 37
         Function evaluations: 555
         Gradient evaluations: 136
Optimization terminated successfully.
         Current function value: 0.000000
         Iterations: 21
         Function evaluations: 224
         Gradient evaluations: 56
Optimization terminated successfully.
         Current function value: 0.000000
         Iterations: 26
         Function evaluations: 255
         Gradient evaluations: 62
Optimization terminated successfully.
         Current function value: 0.000000
         Iterations: 15
         Function evaluations: 136
         Gradient evaluations: 34

starting_points  \
0    [-2.8441227331391516, 0.38471812249222825]   
1      [4.860934917642517, -1.4255444179046108]   
2      [-2.3583708730179334, 2.814342143812407]   
3       [0.5804453294269472, 4.287804990664286]   
4     [0.08008375133428114, -4.546552130217886]   
5      [-3.892805071685962, 1.0435802229490507]   
6    [-2.1614834586087794, -2.9781869550939843]   
7     [-3.3958975137912173, 1.0401877078750799]   
8   [-3.99302658314451, -0.0023894520911484918]   
9      [2.2690035515783187, 2.8926040367723242]   
10    [-2.2336669688360855, 1.1796522324655747]   
11      [1.783723901197308, -4.381743398965049]   
12    [3.5560107290969754, -1.4178754737131527]   
13    [-2.742116449584028, -3.0576108935360633]   
14     [-4.542667003631275, -3.036892103081393]   

                                final_points  iterations  
0   [0.9999940264298028, 0.9999880395814592]          16  
1   [0.9999997709664054, 0.9999995376765878]          25  
2      [1.00000083320153, 1.000001590348009]          37  
3     [1.000002104717729, 1.000004229342567]          21  
4    [1.0000022370719948, 1.000004502892627]          26  
5    [0.9999948396398456, 0.999989669880127]          15  
6   [0.9999955050012177, 0.9999910024647292]          22  
7     [1.000002108984936, 1.000004238135987]          18  
8   [1.0000000097358634, 1.0000000386471393]          10  
9    [1.000004984663821, 1.0000099964474505]          28  
10   [0.9999970882168948, 0.999994175205328]          28  
11  [1.0000020427185627, 1.0000040999444442]          20  
12  [0.9999955176355304, 0.9999910298075042]          35  
13    [1.000001532636625, 1.000003004339988]          25  
14  [0.9999955206041033, 0.9999910280994928]          16

In [99]:
eggcrate_min = runs(eggcrate, len_x=2, up = 2*np.pi, lb = -2*np.pi, number_runs=15)
eggcrate_min

Optimization terminated successfully.
         Current function value: 47.417669
         Iterations: 7
         Function evaluations: 60
         Gradient evaluations: 15
Optimization terminated successfully.
         Current function value: 9.488197
         Iterations: 9
         Function evaluations: 120
         Gradient evaluations: 30
Optimization terminated successfully.
         Current function value: 9.488197
         Iterations: 8
         Function evaluations: 60
         Gradient evaluations: 15
Optimization terminated successfully.
         Current function value: 47.417669
         Iterations: 7
         Function evaluations: 64
         Gradient evaluations: 16
Optimization terminated successfully.
         Current function value: 47.417669
         Iterations: 6
         Function evaluations: 52
         Gradient evaluations: 13
Optimization terminated successfully.
         Current function value: 0.000000
         Iterations: 4
         Function evaluations: 36
    

starting_points  \
0    [-2.662448465038543, -5.026040389325125]   
1    [-4.558866172838427, 2.2580702073218877]   
2      [4.221113551929292, 2.538991836472487]   
3   [-5.958524256359347, -1.8598737558478762]   
4   [-6.152248462249436, -2.5973446965755578]   
5   [0.43670172272162144, 0.5164480031743217]   
6   [-3.261467296736626, -1.6213694590105598]   
7   [3.2300801228633897, -1.8172140615014243]   
8   [0.9071556792807423, -4.8071724728215095]   
9    [-6.146222494893988, 2.7866099183158592]   
10     [2.765125274333103, 5.304388289400782]   
11  [-2.334298843535161, -1.9158008385558691]   
12  [1.5555958463318111, -2.0642557021729218]   
13    [-3.760922327551974, 3.779176732416685]   
14    [-4.542978377992773, 5.269688251476518]   

                                        final_points  iterations  
0          [-3.0196018730543748, -6.031424038755827]           7  
1     [-3.0196018756823935, -1.0406161873872908e-07]           9  
2        [-6.06358606899679e-09, 3.0196018785154894]           8  
3          [-6.031424018681482, -3.0196018910938873]           7  
4           [-6.031424013829912, -3.019601892653317]           6  
5   [-7.284525747016567e-09, -6.395399989069775e-09]           4  
6     [-3.0196018407613745, -1.9480776520746497e-07]          10  
7           [3.019601880917373, -3.0196018921614516]           7  
8   [-5.368083576650219e-09, -7.447311522477494e-09]           7  
9           [-6.031424011822633, 3.0196018794495765]           5  
10             [3.01960172028668, 6.031423834353291]           6  
11          [-3.019601893147507, -3.019601891539982]           6  
12       [-8.94344850723275e-09, -3.019601891785095]           7  
13          [-3.019601895452808, 3.0196018717353463]           3  
14          [-3.0196018978094425, 6.031424017502105]           6